version: '3.8'

services:
  bot:
    container_name: assistant_bot
    image: node:22.4.1
    ports:
      - "8000:8000"
    volumes:
      - /root/assistant-bot:/var/www:ro
    working_dir: /var/www
    command: bash -c "npm install && npm start"
    networks:
      - assistant_network

  mongo:
    container_name: assistant_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "ZkMV2n84TDCZUvx5"
    networks:
      - assistant_network

  mongo-express:
    image: amd64/mongo-express
    container_name: assistant_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: "ZkMV2n84TDCZUvx5"
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_BASICAUTH: false
    networks:
      - assistant_network

networks:
  assistant_network:
    driver: bridge